###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: arquivei-test-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: arquivei-test-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=arquivei-test
      ports:
        - "8892:5432"

    webserver:
      image: nginx:alpine
      container_name: arquivei-test-webserver
      working_dir: /application
      volumes:
          - ./src/src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: arquivei-test-php-fpm
      working_dir: /application
      volumes:
        - ./src/src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

